### ISSUE TITLE
Why have Unknown error while getting Access Token: 504 GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by susubobo** [shamhi/HamsterKombatBot#339]
![image](https://github.com/shamhi/HamsterKombatBot/assets/57805357/34ef741a-a369-4957-94ba-ec6acbfea2f3)

**Comment by fiqi732** [comment]
same sir

**Comment by xshayank** [comment]
This is a duplicate of this issue 

https://github.com/shamhi/HamsterKombatBot/issues/338

**Comment by ButCheR-PRO** [comment]
Problem solution:
1) Log in to this telegram account from any device;
2) Close all sessions with the Pyrogram header
3) Recreate the session inside your bot (instead of a token, use a phone number in international format)
4) Disable proxy or use SOCKS5 instead of HTTP
5) Synchronize the system time on your computer

See also:
1. https://github.com/shamhi/HamsterKombatBot/issues/309
2. https://github.com/shamhi/HamsterKombatBot/issues/38
3. https://github.com/shamhi/HamsterKombatBot/issues/58
4. https://github.com/shamhi/HamsterKombatBot/issues/86
5. https://github.com/shamhi/HamsterKombatBot/issues/137
6. https://github.com/shamhi/HamsterKombatBot/issues/263
