### ISSUE TITLE
Unknown error while getting Access Token: 422, message='Unprocessable Entity', 

### ISSUE THREAD

**Issue by mrdarkerr** [shamhi/HamsterKombatBot#340]
Unknown error while getting Access Token: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: {"type":"validation","on":"body","found":{"initDataRaw":null,"fingerprint":{"visitorId":"5425ed84e59c293f4e30b7161cc85612"}}}...

**Comment by mrdarkerr** [comment]
After disabling the script and passing a few minutes, the problem was solved automatically

**Comment by sharpeye57** [comment]
how to disable the script? mine get that error too, already running a few min still the error exist

**Comment by ButCheR-PRO** [comment]
Problem solution:
1) Log in to this telegram account from any device;
2) Close all sessions with the Pyrogram header
3) Recreate the session inside your bot (instead of a token, use a phone number in international format)
4) Disable proxy or use SOCKS5 instead of HTTP
5) Synchronize the system time on your computer

See also:
1. https://github.com/shamhi/HamsterKombatBot/issues/309
2. https://github.com/shamhi/HamsterKombatBot/issues/38
3. https://github.com/shamhi/HamsterKombatBot/issues/58
4. https://github.com/shamhi/HamsterKombatBot/issues/86
5. https://github.com/shamhi/HamsterKombatBot/issues/137
6. https://github.com/shamhi/HamsterKombatBot/issues/263
